version: '3.8'

services:
  rabbitmq:
    image: rabbitmq
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
    volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/
        - ./rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  test-app:
    build:
      context: .
      dockerfile: Test-app.Dockerfile
    container_name: test-app
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    links:
      - db
      - rabbitmq
  test-app-worker1:
    build:
      context: .
      dockerfile: Test-app-Worker.Dockerfile
    container_name: test-app-worker1
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    links:
      - db
      - rabbitmq

volumes:
  db:
    driver: local